bookrecipes/bookrecipes/urls.py
from django.contrib import admin
from django.urls import path, include
from recipeapp.views import index
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipeapp.urls')),
    path('userapp/', include('userapp.urls')),
]

bookrecipes/recipeapp/urls.py
from django.urls import path
from recipeapp.views import index, recipe_categories, recipe_category

app_name = 'recipeapp'

urlpatterns = [
    path('', index, name='index'),
    path('recipe_categories/', recipe_categories, name='recipe_categories'),
    path('recipe_category/<int:category>/', recipe_category, name='recipe_category'),
]

bookrecipes/userapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from userapp.views import (help_template,
                           rules,
                           advertisement,
                           register_view,
                           login_view,
                           logout_view,
                           profile,
                           )

app_name = 'userapp'

urlpatterns = [
    path('help/', help_template, name='help_template'),
    path('rules/', rules, name='rules'),
    path('advertisement/', advertisement, name='advertisement'),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile, name='profile'),
]

bookrecipes/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>{% block title %}Книга рецептов{% endblock %}</title>
</head>
<body>
<header>
    <div class="menu">
        <div><a href="{% url 'recipeapp:recipe_category' category=1 %}">Торты</a></div>
        <div><a href="{% url 'recipeapp:recipe_category' category=2 %}">Пироги</a></div>
        <div><a href="{% url 'recipeapp:recipe_category' category=3 %}">Печенье</a></div>
        <div><a href="{% url 'recipeapp:recipe_category' category=4 %}">Капкейки</a></div>
        <div><a href="{% url 'recipeapp:recipe_category' category=5 %}">Несладкая выпечка</a></div>
    </div>
    <div class="login">
        {% if user.is_authenticated %}
            <div class="login-active">
                <a class="icon-profile" href="{% url 'userapp:profile' %}">
                    <img src="{% static 'images/icon_profile.svg' %}" alt="profile-icon">
                </a>
                <a href="{% url 'userapp:logout' %}">Выход</a>
            </div>
        {% else %}
            <a href="{% url 'userapp:login' %}">
                <div>Вход <br> Регистрация</div>
            </a>
        {% endif %}
    </div>
</header>

{% block content %}
    <h1>Soon here will be content. Please wait a minute</h1>
{% endblock %}

<footer>
    <div><a href="{% url 'recipeapp:index' %}">Главная</a></div>
    <div><a href="{% url 'userapp:help_template' %}">Помощь</a></div>
    <div><a href="#">Контакты</a></div>
    <div class="extended">
        Почта: <br>
        imbirnyyd@mail.ru <br>
        Телефон: <br>
        8 (49232)1 -23-45
    </div>
    <div><a href="{% url 'recipeapp:recipe_categories' %}">Рецепты</a></div>
    <div><a href="{% url 'userapp:advertisement' %}">Рекламодателям</a></div>
    <div><a href="{% url 'userapp:rules' %}">Правила</a></div>
</footer>
</body>
</html>

bookrecipes/templates/main.html
{% extends 'base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}
<main class="common flex-direct-col">
    <section class="outer-block-slim">
        <div class="top">
            <p>
                <span class="marker">Имбирный домик</span><br>
                Кулинарный проект, в котором <br>
                мы делимся с вами пошаговыми <br>
                рецептами с авторскими <br> фотографиями.
            </p>
        </div>
        <h1>Лучшие рецепты</h1>

        <div class="preview-of-recipe">
            <div class="around-img"><img src="../static/images/roasted-pork-steak-vegetables-plate.jpg" alt="recipe"></div>
            <p>
                <span>Медовик</span><br>
                «Медовик» - один из самых известных десертов классической русской кухни. Он был
                рождён на кухне императорского дворца около двухсот лет назад и с тех пор пользуется
                огромной любовью во всём мире.
            </p>
        </div>
        <div class="preview-of-recipe reverse">
            <div class="around-img"><img src="../static/images/cheese_cake.png" alt="recipe"></div>
            <p>
                <span>Тирамису</span><br>
                «Тирамису» – известный десерт. У слова 3 части – tira mi su. Дословно – «поднимай
                меня вверх». Многие считают, что такое название появилось из-за большого количества
                калорий в десерте. А многие уверены, что название касается эмоций, то есть «подними
                мне настроение».
            </p>
        </div>
        <div class="preview-of-recipe">
            <div class="around-img"><img src="../static/images/roasted-pork-steak-vegetables-plate.jpg" alt="recipe"></div>
            <p>
                <span>Медовик</span><br>
                «Медовик» - один из самых известных десертов классической русской кухни. Он был
                рождён на кухне императорского дворца около двухсот лет назад и с тех пор пользуется
                огромной любовью во всём мире.
            </p>
        </div>
        <div class="preview-of-recipe reverse">
            <div class="around-img"><img src="../static/images/cheese_cake.png" alt="recipe"></div>
            <p>
                <span>Тирамису</span><br>
                «Тирамису» – известный десерт. У слова 3 части – tira mi su. Дословно – «поднимай
                меня вверх». Многие считают, что такое название появилось из-за большого количества
                калорий в десерте. А многие уверены, что название касается эмоций, то есть «подними
                мне настроение».
            </p>
        </div>
        <div class="preview-of-recipe">
            <div class="around-img"><img src="../static/images/roasted-pork-steak-vegetables-plate.jpg" alt="recipe"></div>
            <p>
                <span>Медовик</span><br>
                «Медовик» - один из самых известных десертов классической русской кухни. Он был
                рождён на кухне императорского дворца около двухсот лет назад и с тех пор пользуется
                огромной любовью во всём мире.
            </p>
        </div>


    </section>
    <section class="social-media">
        <h2>Присоединяйтесь к нам в социальных сетях</h2>
        <div class="icons">
            <div class="unit">
                <img src="../static/images/vk.png" alt="social media">
                <span>ВКОНТАКТЕ</span>
            </div>
            <div class="unit">
                <img src="../static/images/instagram.png" alt="social media">
                <span>INSTAGRAM</span>
            </div>
            <div class="unit">
                <img src="../static/images/telegramm.png" alt="social media">
                <span>TELEGRAM</span>
            </div>
            <div class="unit">
                <img src="../static/images/whats_app.png" alt="social media">
                <span>WHATSAPP</span>
            </div>
        </div>
    </section>
</main>
{% endblock %}

bookrecipes/templates/rules.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../static/css/style.css">
    <title>Правила</title>
</head>
<body>
<header>
    <div class="menu">
        <div><a href="#">Торты</a></div>
        <div><a href="#">Пироги</a></div>
        <div><a href="#">Печенье</a></div>
        <div><a href="#">Капкейки</a></div>
        <div><a href="#">Несладкая выпечка</a></div>
    </div>
    <div class="login">
                <div><a href="#">Вход</a></div>
        <div><a href="#">Регистрация</a></div>
    </div>
</header>

<main class="common">
    <section class="outer-block">
        <h1>Правила</h1>

        <h4>Основные понятия:</h4>
        <p>
            Сайт — совокупность веб-страниц, размещенных в сети Интернет и объединенных общим доменным именем edimdoma.ru,
            единой темой, логической структурой, дизайном и оформлением. <br>
            Администрация — правообладатель Сайта <br>
            Пользователь — лицо, осуществляющее доступ к Сайту. <br>
            Результаты интеллектуальной деятельности/Произведения — охраняемые в соответствии с действующим
            законодательством
            Российской Федерации результаты интеллектуальной деятельности и/или средства индивидуализации, созданные
            творческим
            трудом одного или нескольких лиц. Все права на материалы, находящиеся на сайте, охраняются в соответствии с
            действующим законодательством Российской Федерации, в том числе, Частью IV Гражданского Кодекса Российской
            Федерации. Копирование материалов сайта возможно только с разрешения Администрации. <br>
            Персональная страница пользователя — раздел сайта, в котором размещена информация о пользователе, его
            персональные
            данные, рецепты, кулинарная книга, друзья, группы, другая информация. Персональная страница пользователя также
            дает
            возможность другим пользователям отправлять ему личные сообщения, предложения дружбы, а также оставлять
            сообщения,
            доступные для прочтения и комментирования другим пользователям. <br>
            Правообладатель — лицо, обладающее исключительным правом на Результаты интеллектуальной деятельности, либо лицо,
            владеющее исключительной лицензией на использование Результатов интеллектуальной деятельности. <br>
            Настоящее Пользовательское соглашение (далее — Соглашение) регламентируют отношения между Администрацией Сайта и
            Пользователем, касающиеся использования Сайта, обработки персональных данных Пользователя.
        </p>

        <h4>Администрация настоящим дает Пользователю разрешение получить доступ к сервисам сайта и использовать Сайт при
            соблюдении следующих условий:</h4>
        <ul>
            <li>Пользователь не вправе копировать и распространять материалы с Сайта;</li>
            <li>Пользователь не вправе изменять и модифицировать какую-либо часть Сайта;</li>
            <li>Пользователь не вправе размещать на Сайте информацию и объекты (включая ссылки на них), которые могут
                нарушать имущественные и неимущественные права и интересы других лиц;
            </li>
            <li>Пользователь обязуется не совершать и не пытаться совершать следующие действия: вмешиваться в любые
                связанные с безопасностью элементы Сайта или элементы, которые предотвращают или ограничивают использование,
                или копирование любой информации либо налагают ограничения на использование Сайта или информации, доступ к
                которой может быть получен на Сайте.
            </li>
            <li>Пользователь обязуется не использовать Сайт, а также любую информацию и материалы, размещенные на сайте, в
                коммерческих целях без предварительного письменного разрешения Администрации.
            </li>
            <li>Пользователь обязуется не использовать и не вводить никакую автоматизированную систему (включая, среди
                прочего, любого робота, «паука» или автономный считыватель), которая дает доступ к Сайту таким образом, при
                котором на серверы Сайта направляется больше запросов в течение определенного периода времени, чем человек
                может направить в такой же период посредством использования общедоступного стандартного (т. е. не
                модифицированного) веб-браузера;
            </li>
            <li>Пользователь не имеет права осуществлять сбор, хранение, использование и распространение информации о других
                пользователях;
            </li>
            <li>Пользователь может использовать материалы Сайта без получения предварительного согласия Администрации только
                в личных целях.
            </li>
            <li>Цитирование текстов (статей), размещенных на Сайте, возможно исключительно при условии указания Сайта как
                источника и размещении гиперссылки на Сайт, гиперссылка должна располагаться в начале воспроизводимого
                текста (статьи).
            </li>
        </ul>

        <h4>Пользователь обязуется не размещать на Сайте и не направлять куда-либо посредством Сайта любые информацию,
            материалы следующего характера:</h4>
        <p>
            - нарушающие законодательство Российской Федерации, содержащие угрозы, сообщения непристойного характера и/или
            содержащие оскорбляющие и/или дискредитирующие других лиц данные, нарушающие права граждан на неприкосновенность
            личной и частной жизни, посягающие на общественный порядок;<br>
            - содержащие бранные слова, непристойные и оскорбительные образы, сравнения и выражения, в том числе в отношении
            пола, расы, национальности, профессии, социальной категории, возраста, языка человека и гражданина, официальных
            государственных символов (флагов, гербов, гимнов), религиозных символов, объектов культурного наследия
            (памятников истории и культуры);<br>
            - способствующие или содержащие попытки разжигания вражды или призывы к насилию;<br>
            - побуждающие других лиц на противоправное поведение, влекущее уголовную, административную, гражданско-правовую
            и
            иную ответственность или каким-либо образом нарушающие положения законодательства РФ;<br>
            - разглашающие информацию, представляющую или создающие риск для конфиденциальности или безопасности данных
            любого
            лица;<br>
            - содержащие или распространяющие информацию, которая является недостоверной, вводит в заблуждение;<br>
            - содержащие или распространяющие результаты творческой деятельности других лиц, защищенных законодательством об
            интеллектуальной собственности, например, предоставляющие контрафактную продукцию или содержащие ссылки на нее,
            предоставляющие информацию о том, как обойти установленную производителем защиту от копирования;<br>
            - предполагающие пересылку спама или незапрашиваемую массовую рассылку, использование средств моментального
            обмена
            сообщениями, пересылку спама с использованием средств моментального обмена сообщениями или рассылку спама;<br>
            - содержащие изображение человека, размещенное без его разрешения;<br>
            - иные материалы, которые, по мнению Администрации Сайта, нарушают положения настоящего Соглашения.
        </p>

    </section>
</main>

<footer>
    <div><a href="#">Главная</a></div>
    <div><a href="#">Помощь</a></div>
    <div><a href="#">Контакты</a></div>
    <div class="extended">
        Почта: <br>
        imbirnyyd@mail.ru <br>
        Телефон: <br>
        8 (49232)1 -23-45
    </div>
    <div><a href="#">Рецепты</a></div>
    <div><a href="#">Рекламодателям</a></div>
    <div><a href="#">Правила</a></div>
</footer>
</body>
</html>