bookrecipes/bookrecipes/urls.py
from django.contrib import admin
from django.urls import path, include
from recipeapp.views import index
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipeapp.urls')),
    path('userapp/', include('userapp.urls')),
]

bookrecipes/recipeapp/urls.py
from django.urls import path
from recipeapp.views import index, recipe_categories, recipe_category

app_name = 'recipeapp'

urlpatterns = [
    path('', index, name='index'),
    path('recipe_categories/', recipe_categories, name='recipe_categories'),
    path('recipe_category/<int:category>/', recipe_category, name='recipe_category'),
]

bookrecipes/userapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from userapp.views import (help_template,
                           rules,
                           advertisement,
                           register_view,
                           login_view,
                           logout_view,
                           profile,
                           )

app_name = 'userapp'

urlpatterns = [
    path('help/', help_template, name='help_template'),
    path('rules/', rules, name='rules'),
    path('advertisement/', advertisement, name='advertisement'),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile, name='profile'),
]

bookrecipes/userapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# from django.

# Create your models here.

class User(AbstractUser):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    gender = models.CharField(max_length=1, null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    photo = models.ImageField(upload_to='users_photo/', null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'password']

    def __str__(self):
        return (f'User(pk={self.pk}, '
                f'username: {self.username}, '
                f'email: {self.email})')

    def save(self, *args, **kwargs):
        self.set_password(self.password)
        super().save(*args, **kwargs)

bookrecipes/userapp/forms.py
from cProfile import label

from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from .models import User


class UserRegistrationForm(UserCreationForm):
    name = forms.CharField(max_length=50, required=True, label='',
                           widget=forms.TextInput(attrs={'class': 'field', 'placeholder': 'Имя'}))
    email = forms.EmailField(required=True, label='', widget=forms.EmailInput(
        attrs={'class': 'field', 'placeholder': 'E-mail'}))
    password1 = forms.CharField(required=True, label='', widget=forms.PasswordInput(
        attrs={'class': 'field', 'placeholder': 'Пароль'}))
    password2 = forms.CharField(required=True, label='', widget=forms.PasswordInput(
        attrs={'class': 'field', 'placeholder': 'Повторите пароль'}))

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['name', 'email', 'password1', 'password2']


class UserLoginForm(forms.Form):
    email = forms.EmailField(required=True, label='', widget=forms.EmailInput(
        attrs={'class': 'field', 'placeholder': 'E-mail'}))
    password = forms.CharField(label='', widget=forms.PasswordInput(
        attrs={'class': 'field', 'placeholder': 'Пароль'}))


class UserProfileForm(UserChangeForm):
    # name = forms.CharField(max_length=100, label='', widget=forms.TextInput(
    #     attrs={'class': 'personal-field', 'placeholder': 'Имя'}), required=False)
    # email = forms.EmailField(label='', widget=forms.EmailInput(
    #     attrs={'class': 'personal-field', 'placeholder': 'E-mail', 'required': True}))
    # gender = forms.CharField(label='', max_length=1, widget=forms.TextInput(
    #     attrs={'class': 'personal-field', 'placeholder': 'Пол'}), required=False)
    # birthday = forms.DateField(label='', widget=forms.DateInput(
    #     attrs={'class': 'personal-field', 'placeholder': 'Дата рождения', 'type': 'date'}), required=False)
    # photo = forms.ImageField(label='', widget=forms.FileInput(
    #     attrs={'class': 'personal-field', 'placeholder': 'Ваше фото'}), required=False)

    class Meta:
        model = User
        fields = ['name', 'email', 'gender', 'birthday']

bookrecipes/userapp/views.py
from lib2to3.fixes.fix_input import context
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
# from django.urls import reverse

from .models import User
from .forms import UserRegistrationForm, UserLoginForm, UserProfileForm


# Create your views here.


def advertisement(request: HttpRequest):
    # print(request.path)
    # print(request.method)
    # print(request.headers)
    return render(request, 'userapp/advertisement.html')


def help_template(request):
    return render(request, 'userapp/help.html')


def rules(request):
    return render(request, 'userapp/rules.html')


def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('userapp:profile'))
    else:
        form = UserProfileForm(instance=request.user)
    context = {'form': form}
    return render(request, 'userapp/profile.html', context)


def register_view(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            password = form.cleaned_data['password1']
            email = form.cleaned_data['email']
            username = email
            user = User(username=username, name=name, email=email, password=password)
            user.save()
            login(request, user)
            return render(request, 'recipeapp/index.html', {'form': form})
    else:
        form = UserRegistrationForm()
    return render(request, 'userapp/register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                return redirect('recipeapp:index')
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'userapp/login.html', context)


def logout_view(request: HttpRequest):
    logout(request)
    return redirect('recipeapp:index')

bookrecipes/userapp/templates/userapp/advertisement.html
{% extends 'base.html' %}

{% block title %}Рекламодатеям{% endblock %}

{% block content %}
    <main class="common">
        <section class="outer-block">
            <h1>Рекламодателям</h1>

            <h4>Рекламные возможности:</h4>
            <p>
                Брендирование и баннерная реклама — классические форматы, а также мобильные форматы.
                <br>
                Спецпроекты — размещение PR статей, фотоконкурсы/конкурсы рецептов.
            </p>

            <h4>Рекламная статья</h4>
            <p>
                Один из вариантов размещение рекламы на проекте art-lunch.ru происходит путем
                публикации статей о вашей компании, товарах или услугах. Статьи могут быть написаны
                в
                виде советов, отзывов или иметь общий информационный характер. Размещается анонс на
                главной странице минимум на 14 дней. Статьи размещаются на постоянной основе и дают
                рекламодателю продолжительный эффект.
                <br>
                Статья предоставляется заказчиком в формате txt или doc в окончательно
                отредактированном
                виде. Объем текста статьи — до 10 000 символов. Внутри текста могут быть размещены
                до
                3-х ссылок на сайт заказчика. Графические изображения: 4-5 штук предоставляются
                заказчиком в одном из форматов gif/jpeg/png. Стоимость 3 000 рублей.
            </p>

            <h4>Интеграция бренда в рецепты</h4>
            <p>
                Предполагает использование рекламируемого продукта заказчика в рецепте. Стоимость 40
                000
                рублей за 5 рецептов, длительность акции 1 год. <br>
                — Рецепт или производится с использованием рекламируемого продукта заказчика (если
                продукт редкий или дорогой, то предоставляется заказчиком) или ингредиент
                интегрируется
                в уже существующий рецепт на сайте (рецепт переснимается с рекламируемым продуктом).
                <br> —
                Название продукта присутствует по тексту рецепта и в исходных ингредиентах. <br> —
                Анонс
                фото-рецепта с рекламируемым продуктом размещается на 1 месяц на главной странице
                сайта. <br> — На финальной фотографии готового блюда возможно размещение
                рекламируемого
                продукта. <br> — Редакция в праве отказать заказчику, если рекламируемый продукт
                ненадлежащего качества.
            </p>

            <h4>Другие рекламные возможности</h4>
            <p>
                — Создание брендированной страницы или целого раздела вашей компании, её размещение
                и
                реклама; <br> — Ведение ваших специальных и промо-проектов на сайте; <br> —
                Спонсорство
                разделов сайта.
            </p>

            <h4 class="end">По вопросам размещения рекламы на art-lunch.ru обращайтесь по
                электронной почте:
                imbirnyyd@mail.ru</h4>

        </section>
    </main>
{% endblock %}

bookrecipes/userapp/templates/userapp/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>{% block title %}Книга рецептов{% endblock %}</title>
</head>
<body>
<header>
    <div class="menu">
        <div><a href="#">Торты</a></div>
        <div><a href="#">Пироги</a></div>
        <div><a href="#">Печенье</a></div>
        <div><a href="#">Капкейки</a></div>
        <div><a href="#">Несладкая выпечка</a></div>
    </div>
    <div class="login" style="display: none">
        {% if user.is_authenticated %}
            <div><a href="{% url 'userapp:logout' %}">Выход</a></div>
        {% else %}
            <a href="{% url 'userapp:login' %}"><div>Вход <br> Регистрация</div></a>
        {% endif %}
    </div>
</header>

{% block content %}
    <h1>Soon here will be content. Please wait a minute</h1>
{% endblock %}

<footer>
    <div><a href="{% url 'recipeapp:index' %}">Главная</a></div>
    <div><a href="{% url 'userapp:help_template' %}">Помощь</a></div>
    <div><a href="#">Контакты</a></div>
    <div class="extended">
        Почта: <br>
        imbirnyyd@mail.ru <br>
        Телефон: <br>
        8 (49232)1 -23-45
    </div>
    <div><a href="{% url 'recipeapp:recipe_categories' %}">Рецепты</a></div>
    <div><a href="{% url 'userapp:advertisement' %}">Рекламодателям</a></div>
    <div><a href="{% url 'userapp:rules' %}">Правила</a></div>
</footer>
</body>
</html>

bookrecipes/userapp/templates/userapp/help.html
{% extends 'base.html' %}

{% block title %}Помощь{% endblock %}

{% block content %}
    <main class="common">
        <section class="outer-block">
            <h1>Помощь</h1>
            <h4>Регистрация</h4>
            <p>
                Что делать, если вы не получили письмо с подтверждением регистрации? Такое может
                случиться по нескольким причинам. Либо письмо попало в спам, либо вы неправильно
                ввели
                свой email при заполнении формы редактирования. Напишите нам о возникшей проблеме
                на support@edimdoma.ru, указав свой
                e-mail и имя пользователя
            </p>

            <h4>Публикация рецепта</h4>
            <p>
                Создание и публикация рецепта — 1 балл<br>
                Описание к рецепту — 1 балл к публикации<br>
                Фото в шагах рецепта — 1 балл к публикации за каждое пошаговое фото<br>
                Добавление ингредиента к шагу (необязательно для публикации рецепта) — 1 балл к
                публикации рецепта<br>
                Рецепт дня (если ваш рецепт стал Рецептом дня) — 10 баллов<br>
                Рецепт месяца (если ваш рецепт стал Рецептом месяца) — 100 баллов<br>
                Добавление рецепта в кулинарную книгу (если ваш рецепт добавил к себе в книгу другой
                пользователь) — 1 балл автору рецепта<br>
                Добавление фотоотчета к рецепту (если вы добавили фотоотчет к рецепту другого
                пользователя, учитывается факт добавления, а не количество добавленных к фотографии)
                — 5 баллов автору фотоотчета<br>
                Если рецепт был убран автором в черновики или удален с сайта, то с автора снимаются
                все
                баллы, ранее начисленные за этот рецепт.
            </p>

            <h4>Публикация постов</h4>
            <p>Создание и публикация поста — 3 балла</p>

            <h4>Комментарии</h4>
            <p>Добавления комментария (если вы написали комментарий к рецепту, посту, фотографии и
                т.д.)
                — 1 балл автору комментария</p>

            <h4>Конкурсы</h4>
            <p>
                Участие в конкурсе — 1 балл<br>
                Победа в конкурсе (если ваш рецепт стал одним из победителей в конкурсе) — 10 баллов<br>
                Примечание: ранее за участие в конкурсах баллы не начислялись, пересчет рейтинга
                авторов
                с учетом новой позиции был сделан за все конкурсы, которые на данный момент есть в
                разделах «Архив конкурсов».
            </p>

            <h4>Кулинарные битвы</h4>
            <p>
                Участие в битве (если в битву оба участника загрузили рецепты, и битва состоялась) —
                1
                балл<br>
                Победа (если ваш рецепт стал победителем битвы) — 3 балла<br>
                Примечание: ранее за кулинарные битвы баллы не начислялись, пересчет рейтинга с
                учетом
                новой позиции был сделан за все состоявшиеся битвы на сайте, в которых есть
                победитель.
                Напоминаем, что автор может принимать участие во внутренних голосованиях на сайте,
                когда
                его рейтинг достигает 100 баллов.
            </p>

        </section>
    </main>
{% endblock %}

bookrecipes/userapp/templates/userapp/login.html
{% extends 'userapp/base.html' %}

{% block title %}Вход{% endblock %}

{% block content %}
    <main class="reg-login">
        <div class="headline-reg">Вход</div>
        <div class="registration">
            <form class="form" method="post">
                {% csrf_token %}
                {{ form }}
{#                    <label for="email"></label>#}
{#                    <input id="email" class="field" type="email" placeholder="E-mail" name="email"#}
{#                           required>#}
{#                    <label for="username"></label>#}
{#                    <input id="username" class="field" type="text" placeholder="E-mail" name="username"#}
{#                           required>#}
{#                    <label for="password"></label>#}
{#                    <input id="password" class="field" type="password" placeholder="Пароль"#}
{#                           name="password" required>#}
                <input class="post" type="submit" value="Войти">
                <a class="post" href="{% url 'userapp:register' %}">Зарегистрироваться</a>
            </form>
        </div>
        <div>
            {% if error %}
                {{ error }}
            {% endif %}
        </div>
    </main>
{% endblock %}

bookrecipes/userapp/templates/userapp/profile.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Личный кабинет{% endblock %}

{% block content %}
    <main class="common">
        <section class="outer-block min-height">
            {% if user.is_authenticated %}
                <h1>Личный кабинет</h1>

                <div class="personal-area">
                    <form class="form-pa" method="post" action="{% url 'userapp:profile' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="around-img"><img src="{% static 'images/private_area.png' %}" alt="private area"></div>
{#                        {{ form }}#}
                        {{ form.name }}
                        {{ form.email }}
{#                        {{ form.birthday.value }}#}
                        {{ form.birthday }}
                        {{ user.photo.url }}
                        {{ form.gender }}
                        {{ form.photo }}
                        <input class="login" type="submit" value="Сохранить">
                    </form>
                </div>

                <div class="add-recipe-button">
                    <img src="{% static 'images/plus.png' %}" alt="plus">
                    <a href="#">
                        <div>ДОБАВИТЬ <br> РЕЦЕПТ</div>
                    </a>
                </div>

                <img class="fix-img-footer" src="{% static 'images/cookies_footer.png' %}"
                     alt="cookies">
                </section>
            {% else %}
                <h1>Войдите в личный кабинет</h1>
            {% endif %}
    </main>
{% endblock %}

bookrecipes/userapp/templates/userapp/register.html
{% extends 'userapp/base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <main class="reg-login">
        <div class="headline-reg">Регистрация</div>
        <div class="registration">
            <form class="form" method="post">
                {% csrf_token %}
                {{ form }}
{#                <label for="name"></label>#}
{#                <input id="name" class="field" type="text" placeholder="Имя" name="{{ form.name }}" required>#}
{#                <label for="email"></label>#}
{#                <input id="email" class="field" type="email" placeholder="E-mail" name="{{ form.email }}"#}
{#                       required>#}
{#                <label for="password1"></label>#}
{#                <input id="password1" class="field" type="password" placeholder="Пароль"#}
{#                       name="{{ form.password1 }}" required>#}
{#                <label for="password2"></label>#}
{#                <input id="{{ form.password2 }}" class="field" type="password"#}
{#                       placeholder="Подтвердите пароль" name="password" required>#}
                <input class="post" type="submit" value="Зарегистрироваться">
                <a class="post" href="{% url 'userapp:login' %}">Войти в личный кабинет</a>
            </form>
        </div>

    </main>
{% endblock %}

bookrecipes/userapp/templates/userapp/registration.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <main class="reg-login">
        <div class="headline-reg">Регистрация</div>
        <div class="registration">
            <form class="form" method="post">
                {% csrf_token %}
                {{ form }}
{#                <label for="name"></label>#}
{#                <input id="name" class="field" type="text" placeholder="Имя" name="name" required>#}
{#                <label for="email"></label>#}
{#                <input id="email" class="field" type="email" placeholder="E-mail" name="email"#}
{#                       required>#}
{#                <label for="password1"></label>#}
{#                <input id="password1" class="field" type="password" placeholder="Пароль"#}
{#                       name="password" required>#}
{#                <label for="password2"></label>#}
{#                <input id="password2" class="field" type="password"#}
{#                       placeholder="Подтвердите пароль" name="password" required>#}
                <input class="post" type="submit" value="Зарегистрироваться">
            </form>
        </div>

    </main>
{% endblock %}

bookrecipes/userapp/templates/userapp/rules.html
{% extends 'base.html' %}

{% block title %}Правила{% endblock %}

{% block content %}
<main class="common">
    <section class="outer-block">
        <h1>Правила</h1>

        <h4>Основные понятия:</h4>
        <p>
            Сайт — совокупность веб-страниц, размещенных в сети Интернет и объединенных общим доменным именем edimdoma.ru,
            единой темой, логической структурой, дизайном и оформлением. <br>
            Администрация — правообладатель Сайта <br>
            Пользователь — лицо, осуществляющее доступ к Сайту. <br>
            Результаты интеллектуальной деятельности/Произведения — охраняемые в соответствии с действующим
            законодательством
            Российской Федерации результаты интеллектуальной деятельности и/или средства индивидуализации, созданные
            творческим
            трудом одного или нескольких лиц. Все права на материалы, находящиеся на сайте, охраняются в соответствии с
            действующим законодательством Российской Федерации, в том числе, Частью IV Гражданского Кодекса Российской
            Федерации. Копирование материалов сайта возможно только с разрешения Администрации. <br>
            Персональная страница пользователя — раздел сайта, в котором размещена информация о пользователе, его
            персональные
            данные, рецепты, кулинарная книга, друзья, группы, другая информация. Персональная страница пользователя также
            дает
            возможность другим пользователям отправлять ему личные сообщения, предложения дружбы, а также оставлять
            сообщения,
            доступные для прочтения и комментирования другим пользователям. <br>
            Правообладатель — лицо, обладающее исключительным правом на Результаты интеллектуальной деятельности, либо лицо,
            владеющее исключительной лицензией на использование Результатов интеллектуальной деятельности. <br>
            Настоящее Пользовательское соглашение (далее — Соглашение) регламентируют отношения между Администрацией Сайта и
            Пользователем, касающиеся использования Сайта, обработки персональных данных Пользователя.
        </p>

        <h4>Администрация настоящим дает Пользователю разрешение получить доступ к сервисам сайта и использовать Сайт при
            соблюдении следующих условий:</h4>
        <ul>
            <li>Пользователь не вправе копировать и распространять материалы с Сайта;</li>
            <li>Пользователь не вправе изменять и модифицировать какую-либо часть Сайта;</li>
            <li>Пользователь не вправе размещать на Сайте информацию и объекты (включая ссылки на них), которые могут
                нарушать имущественные и неимущественные права и интересы других лиц;
            </li>
            <li>Пользователь обязуется не совершать и не пытаться совершать следующие действия: вмешиваться в любые
                связанные с безопасностью элементы Сайта или элементы, которые предотвращают или ограничивают использование,
                или копирование любой информации либо налагают ограничения на использование Сайта или информации, доступ к
                которой может быть получен на Сайте.
            </li>
            <li>Пользователь обязуется не использовать Сайт, а также любую информацию и материалы, размещенные на сайте, в
                коммерческих целях без предварительного письменного разрешения Администрации.
            </li>
            <li>Пользователь обязуется не использовать и не вводить никакую автоматизированную систему (включая, среди
                прочего, любого робота, «паука» или автономный считыватель), которая дает доступ к Сайту таким образом, при
                котором на серверы Сайта направляется больше запросов в течение определенного периода времени, чем человек
                может направить в такой же период посредством использования общедоступного стандартного (т. е. не
                модифицированного) веб-браузера;
            </li>
            <li>Пользователь не имеет права осуществлять сбор, хранение, использование и распространение информации о других
                пользователях;
            </li>
            <li>Пользователь может использовать материалы Сайта без получения предварительного согласия Администрации только
                в личных целях.
            </li>
            <li>Цитирование текстов (статей), размещенных на Сайте, возможно исключительно при условии указания Сайта как
                источника и размещении гиперссылки на Сайт, гиперссылка должна располагаться в начале воспроизводимого
                текста (статьи).
            </li>
        </ul>

        <h4>Пользователь обязуется не размещать на Сайте и не направлять куда-либо посредством Сайта любые информацию,
            материалы следующего характера:</h4>
        <p>
            - нарушающие законодательство Российской Федерации, содержащие угрозы, сообщения непристойного характера и/или
            содержащие оскорбляющие и/или дискредитирующие других лиц данные, нарушающие права граждан на неприкосновенность
            личной и частной жизни, посягающие на общественный порядок;<br>
            - содержащие бранные слова, непристойные и оскорбительные образы, сравнения и выражения, в том числе в отношении
            пола, расы, национальности, профессии, социальной категории, возраста, языка человека и гражданина, официальных
            государственных символов (флагов, гербов, гимнов), религиозных символов, объектов культурного наследия
            (памятников истории и культуры);<br>
            - способствующие или содержащие попытки разжигания вражды или призывы к насилию;<br>
            - побуждающие других лиц на противоправное поведение, влекущее уголовную, административную, гражданско-правовую
            и
            иную ответственность или каким-либо образом нарушающие положения законодательства РФ;<br>
            - разглашающие информацию, представляющую или создающие риск для конфиденциальности или безопасности данных
            любого
            лица;<br>
            - содержащие или распространяющие информацию, которая является недостоверной, вводит в заблуждение;<br>
            - содержащие или распространяющие результаты творческой деятельности других лиц, защищенных законодательством об
            интеллектуальной собственности, например, предоставляющие контрафактную продукцию или содержащие ссылки на нее,
            предоставляющие информацию о том, как обойти установленную производителем защиту от копирования;<br>
            - предполагающие пересылку спама или незапрашиваемую массовую рассылку, использование средств моментального
            обмена
            сообщениями, пересылку спама с использованием средств моментального обмена сообщениями или рассылку спама;<br>
            - содержащие изображение человека, размещенное без его разрешения;<br>
            - иные материалы, которые, по мнению Администрации Сайта, нарушают положения настоящего Соглашения.
        </p>

    </section>
</main>

{% endblock %}